server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
zuul:
  prefix: /api
  routes:
    test:
      path: /redirect/**
      url: http://google.com